apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-bookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-bookstore
  template:
    metadata:
      labels:
        app: go-bookstore
    spec:
      containers:
      - name: go-bookstore
        image: go-bookstore:latest
        ports:
        - containerPort: 8080
