apiVersion: v1
kind: Service
metadata:
  name: go-bookstore-service
spec:
  type: NodePort
  selector:
    app: go-bookstore
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30008
